# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://hassoun.github.io/artemis_api_python/"

git_url = "https://github.com/hassoun/artemis_api_python/tree/main/"

def custom_doc_links(name): return None
