# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"APIClient": "00_client.ipynb",
         "Sensor": "01_sensor.ipynb",
         "Metric": "02_metric.ipynb",
         "SensorData": "03_sensor_data.ipynb"}

modules = ["client.py",
           "sensor.py",
           "metric.py",
           "sensor_data.py"]

doc_url = "https://Vincent.github.io/artemis_api_python/"

git_url = "https://github.com/Vincent/artemis_api_python/tree/main/"

def custom_doc_links(name): return None
