# AUTOGENERATED! DO NOT EDIT! File to edit: 00_client.ipynb (unless otherwise specified).

__all__ = ['APIClient']

# Cell
import os
from requests_oauthlib import OAuth2Session
from dotenv import load_dotenv

# Cell
load_dotenv(dotenv_path='/Users/vincent/Documents/envvars/cred.env')

# Cell
class APIClient:
    "API Client that enables to authenticate and connect to the `Artemis API`. You need to create an instance of the client to be able to interact with the API"
    def __init__(self, token=None, auth_code=None,
                 redirect_uri=None, on_token_refreshed=None, on_token_failed=None):

        if (token is None) & (auth_code is None):
            raise ValueError('You must either provide your token or an authorization code.')

        self.app_id = os.environ['ARTEMIS_OAUTH_APP_ID']
        self.app_secret = os.environ['ARTEMIS_OAUTH_APP_SECRET']
        self.base_uri = os.environ['ARTEMIS_BASE_URI']
        self.authorization_base_url = f"{self.base_uri}/oauth/authorize"
        self.token_url = f"{self.base_uri}/oauth/token"
        self.refresh_url = self.token_url
        self.url_prefix = '/api/v3'

        if auth_code is not None:
            self.redirect_uri = 'urn:ietf:wg:oauth:2.0:oob' if redirect_uri is None else redirect_uri
            self.oauth_client = OAuth2Session(self.app_id, redirect_uri=self.redirect_uri)
            authorization_response = f"{self.base_uri}/oauth/authorize/native?code={auth_code}"
            self.token = self.oauth_client.fetch_token(
                self.token_url,
                authorization_response=authorization_response,
                client_secret=self.app_secret)
        else:
            self.oauth_client = OAuth2Session(self.app_id, token=token)
            self.token = self.oauth_client.refresh_token(self.refresh_url, client_id=self.app_id, client_secret=self.app_secret)

        self.access_token = self.token.get('access_token')
        self.token_type = self.token.get('token_type')
        self.refresh_token = self.token.get('refresh_token')
        self.expires_at = self.token.get('expires_at')

    def set_url(self, url):
        "Process a url and sets it accordingly for the API calls. The base_url and the url_prefix will be concatenated (preceed) the url"
        return f'{self.base_uri}{self.url_prefix}{url}'

    def get(self, url):
        "Performs a GET request for the url"
        headers = {"Content-Type": "application/json"}
        return self.oauth_client.get(self.set_url(url), headers=headers)

    def post(self, url, data):
        "Performs a POST request for the url and parameters"
        headers = {"Content-Type": "application/json"}
        return self.oauth_client.post(self.set_url(url), data=data, headers=headers)

    def put(self, url, data):
        "Performs a PUT request for the url and parameters"
        headers = {"Content-Type": "application/json"}
        return self.oauth_client.put(self.set_url(url), data=data, headers=headers)

    def delete(self, url):
        "Performs a DELETE request for the url"
        headers = {"Content-Type": "application/json"}
        return self.oauth_client.delete(self.set_url(url), headers=headers)

    def status_handler(self, response):
        "Handles API responses depending on status code"
        return None
