# AUTOGENERATED! DO NOT EDIT! File to edit: 08_completions.ipynb (unless otherwise specified).

__all__ = ['Completions']

# Cell
import json

# Cell
class Completions:
    "`Artemis API` Completions entity object"
    def __init__(self, client):
        self.client = client
        self.response = None

    def find(self, facility_id, completion_id):
        "Retrieves a specific batch completion"
        self.response = self.client.get(f'/facilities/{facility_id}/completions/{completion_id}')
        return self.client.response_handler(self.response)

    def find_specific(self, facility_id, filters=[]):
        "Retrieves a  list of batch completions matching a specific criteria"
        filters_string = self.client.format_filters(filters)
        self.response = self.client.get(f'/facilities/{facility_id}/completions?{filters_string}')
        return self.client.response_handler(self.response)

    def create(self, facility_id, attributes, relationships=None):
        "Creates a new completion"
        data = {}
        body = {}
        data['type'] = "completions"
        data['attributes'] = attributes
        if relationships is not None:
            data['relationships'] = relationships
        body['facility_id'] = facility_id
        body['_jsonapi'] = {}
        body['_jsonapi']['data'] = data
        self.response = self.client.post(f'/facilities/{facility_id}/completions', json.dumps(body))
        return self.client.response_handler(self.response, body)

    def remove(self, facility_id, completion_id):
        "Deletes a specific completion"
        self.response = self.client.delete(f'/facilities/{facility_id}/completions/{completion_id}')
        return self.client.response_handler(self.response)