# AUTOGENERATED! DO NOT EDIT! File to edit: 05_metrics_data.ipynb (unless otherwise specified).

__all__ = ['MetricsData']

# Cell
import json

# Cell
class MetricsData:
    "`Artemis API` MetricsData entity object"
    def __init__(self, client):
        self.client = client
        self.response = None

    def find(self, facility_id, metric_id):
        "Retrieves a list of metrics data points for a specific metric"
        self.response = self.client.get(f'/facilities/{facility_id}/metrics/{metric_id}/data')
        return self.client.response_handler(self.response)

    def create(self, facility_id, metric_id, attributes):
        "Creates a new metric data point for a specific metric"
        data = {}
        body = {}
        data['type'] = "dots"
        data['attributes'] = attributes
        body['facility_id'] = facility_id
        body['metric_id'] = metric_id
        body['_jsonapi'] = {}
        body['_jsonapi']['data'] = data
        self.response = self.client.post(f'/facilities/{facility_id}/metrics/{metric_id}/data', json.dumps(body))
        return self.client.response_handler(self.response, body)

    def remove(self, facility_id, metric_id, dot_id):
        "Deletes a specific metric data point for a specific metric and facility"
        self.response = self.client.delete(f'/facilities/{facility_id}/metrics/{metric_id}/data/{dot_id}')
        return self.client.response_handler(self.response)
