# AUTOGENERATED! DO NOT EDIT! File to edit: 01_sensor.ipynb (unless otherwise specified).

__all__ = ['Sensor']

# Cell
import json

# Cell
class Sensor:
    "`Artemis API` Sensor entity object"
    def __init__(self, client):
        self.client = client
        self.response = None

    def find_all(self, facility_id):
        "Retrieves all sensors for a specific facility"
        self.response = self.client.get(f'/facilities/{facility_id}/sensors')
        try:
            self.response.json().get('data')
        except:
            print(f"Request Failed - {self.response.status_code}: {self.response.reason}")
            return None
        return self.response.json().get('data')

    def find(self, facility_id, sensor_id):
        "Retrieves a specific sensor for a specific facility"
        self.response = self.client.get(f'/facilities/{facility_id}/sensors/{sensor_id}')
        try:
            self.response.json().get('data')
        except:
            print(f"Request Failed - {self.response.status_code}: {self.response.reason}")
            return None
        return self.response.json().get('data')

    def create(self, facility_id, attributes):
        "Creates a new sensor for a specific facility"
        data = {}
        body = {}
        data['type'] = "sensors"
        data['attributes'] = attributes
        body['facility_id'] = facility_id
        body['_jsonapi'] = {}
        body['_jsonapi']['data'] = data
        self.response = self.client.post(f'/facilities/{facility_id}/sensors', json.dumps(body))
        try:
            self.response.json().get('data')
        except:
            print(f"Request Failed - {self.response.status_code}: {self.response.reason}")
            return None
        return self.response.json().get('data')

    def update(self, facility_id, sensor_id, attributes):
        "Updates an existing sensor for a specific facility"
        data = {}
        body = {}
        data['type'] = "sensors"
        data['attributes'] = attributes
        body['facility_id'] = facility_id
        body['id'] = sensor_id
        body['_jsonapi'] = {}
        body['_jsonapi']['data'] = data
        self.response = self.client.put(f'/facilities/{facility_id}/sensors/{sensor_id}', json.dumps(body))
        try:
            self.response.json().get('data')
        except:
            print(f"Request Failed - {self.response.status_code}: {self.response.reason}")
            return None
        return self.response.json().get('data')

    def remove(self, facility_id, sensor_id):
        "Deletes a specific sensor for a specific facility"
        self.response = self.client.delete(f'/facilities/{facility_id}/sensors/{sensor_id}')
        try:
            self.response.json().get('data')
        except:
            print(f"Request Failed - {self.response.status_code}: {self.response.reason}")
            return None
        return self.response.json().get('data')
