# AUTOGENERATED! DO NOT EDIT! File to edit: 03_sensor_data.ipynb (unless otherwise specified).

__all__ = ['SensorData']

# Cell
import json

# Cell
class SensorData:
    "`Artemis API` Sensor Data entity object"
    def __init__(self, client):
        self.client = client
        self.response = None

    def create(self, facility_id, sensor_id, metric_id, attributes):
        "Creates sensor data points for a specific facility, sensor and metric"
        data = {}
        body = {}
        data['type'] = "sensor_data"
        data['attributes'] = attributes
        body['facility_id'] = facility_id
        body['sensor_id'] = sensor_id
        body['metric_id'] = metric_id
        body['_jsonapi'] = {}
        body['_jsonapi']['data'] = data
        self.response = self.client.post(f'/facilities/{facility_id}/sensors/{sensor_id}/sensor_data', json.dumps(body))
        return self.client.response_handler(self.response, body)

    def remove(self, facility_id, sensor_id, metric_id, time_stamp):
        "Deletes a specific sensor data point for a specific facility, sensor, metric and time_stamp"
        body = {}
        body['facility_id'] = facility_id
        body['sensor_id'] = sensor_id
        body['metric_id'] = metric_id
        body['recorded_at'] = time_stamp
        self.response = self.client.delete(f'/facilities/{facility_id}/sensors/{sensor_id}/sensor_data/{time_stamp}', json.dumps(body))
        return self.client.response_handler(self.response, body)
