# AUTOGENERATED! DO NOT EDIT! File to edit: 01_sensor.ipynb (unless otherwise specified).

__all__ = ['Sensor']

# Cell
import os
from requests_oauthlib import OAuth2Session
from dotenv import load_dotenv

# Cell
load_dotenv(dotenv_path='/Users/vincent/Documents/envvars/cred.env')

# Cell
class Sensor:
    "`Artemis API` Sensor entity object"
    def __init__(self, client): self.client = client

    def get_all(self, facility_id):
        "Retrieves all sensors for a specific facility"
        return self.client.get(f'/facilities/{facility_id}/sensors')

    def get(self, facility_id, sensor_id):
        "Retrieves a specific sensor for a specific facility"
        return self.client.get(f'/facilities/{facility_id}/sensors/{sensor_id}')
