# AUTOGENERATED! DO NOT EDIT! File to edit: 06_tanks.ipynb (unless otherwise specified).

__all__ = ['Tanks']

# Cell
import json

# Cell
class Tanks:
    "`Artemis API` Tanks entity object"
    def __init__(self, client):
        self.client = client
        self.response = None

    def find_all(self, facility_id):
        "Retrieves all tanks for a specific facility"
        self.response = self.client.get(f'/facilities/{facility_id}/tanks')
        return self.client.response_handler(self.response)

    def find(self, facility_id, tank_id):
        "Retrieves a  for a specific metric"
        self.response = self.client.get(f'/facilities/{facility_id}/tanks/{tank_id}')
        return self.client.response_handler(self.response)

    def create(self, facility_id, attributes):
        "Creates a new tank for a pecific facility"
        data = {}
        body = {}
        data['type'] = "tanks"
        data['attributes'] = attributes
        body['facility_id'] = facility_id
        body['_jsonapi'] = {}
        body['_jsonapi']['data'] = data
        self.response = self.client.post(f'/facilities/{facility_id}/tanks', json.dumps(body))
        return self.client.response_handler(self.response, body)

    def update(self, facility_id, tank_id, attributes):
        "Updates an existing tank for a specific facility"
        data = {}
        body = {}
        data['type'] = "tanks"
        data['attributes'] = attributes
        body['facility_id'] = facility_id
        body['id'] = tank_id
        body['_jsonapi'] = {}
        body['_jsonapi']['data'] = data
        self.response = self.client.put(f'/facilities/{facility_id}/tanks/{tank_id}', json.dumps(body))
        return self.client.response_handler(self.response, body)

    def remove(self, facility_id, tank_id):
        "Deletes a specific tank for a specific facility"
        self.response = self.client.delete(f'/facilities/{facility_id}/tanks/{tank_id}')
        return self.client.response_handler(self.response)