# AUTOGENERATED! DO NOT EDIT! File to edit: 07_tank_readings.ipynb (unless otherwise specified).

__all__ = ['TankReadings']

# Cell
import json

# Cell
class TankReadings:
    "`Artemis API` TankReadings entity object"
    def __init__(self, client):
        self.client = client
        self.response = None

    def create(self, facility_id, tank_id, attributes, meta):
        "Creates a new tank readings for specific tank metrics (specified in meta)"
        data = {}
        body = {}
        data['type'] = "tank_readings"
        data['attributes'] = attributes
        data['meta'] = meta
        body['facility_id'] = facility_id
        body['tank_id'] = tank_id
        body['_jsonapi'] = {}
        body['_jsonapi']['data'] = data
        self.response = self.client.post(f'/facilities/{facility_id}/tanks/{tank_id}/tank_readings', json.dumps(body))
        return self.client.response_handler(self.response, body)